apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-init-configmap
data:
  init.sh: |-
    touch /etc/docker/daemon.json
    echo "eyJkbnMiOiBbIjguOC44LjgiLCAiOC44LjQuNCJdfQ==" | base64 -d | tee /etc/docker/daemon.json
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  namespace: default
spec:
  initContainers:
    - name: ubuntu-init
      image: ubuntu
      command: ['sh', '/var/init.sh']
      volumeMounts:
        - mountPath: /etc/docker
          name: docker-config
        - name: init-script
          mountPath: /var/init.sh
          subPath: init.sh
      resources:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
  containers:
  - image: so1s/torch-build:v1
    imagePullPolicy: Always
    name: ubuntu
    command:
      - "sleep"
      - "604800"
    resources:
      limits:
        cpu: "1000m"
        memory: "1000Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
        readOnly: true
      - mountPath: /etc/docker
        name: docker-config
        readOnly: true
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  tolerations:
    - key: kind
      operator: "Equal"
      value: "public"
      effect: "NoSchedule"
  volumes:
    - name: docker-config
      emptyDir: {}
    - hostPath:
        path: /var/run/docker.sock
        type: Socket
      name: docker-sock
    - name: init-script
      configMap:
        name: ubuntu-init-configmap
  restartPolicy: Always